### ISSUE TITLE
Want to Create Full Readme File

### ISSUE THREAD

**Issue by maityamit** [Anni1123/Android-Projects#1]
I want to create the Readme file of the following Projects in a stylish manner . 
I want to create .
Because you have made a projects but it has not proper documentation ..
So , **If you say then I will do**

**Comment by maityamit** [comment]
Your Readme File is not looking Good

**Comment by Anni1123** [comment]
Yes Sure! You can proceed

**Comment by maityamit** [comment]
ok , Thank you
